'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Company
    
    '''<summary>
    '''GVCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVCompany As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCompany As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCity As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSDistrict As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCountry As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSCompDet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCompDet As Global.System.Web.UI.WebControls.SqlDataSource
End Class
