'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Members
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''GVMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVMembers As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSDistrict As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSRelation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSRelation As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSChildType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSChildType As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSInterest As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSRetired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSRetired As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCity As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSWDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSWDistrict As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSWCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSWCity As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSParish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSParish As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMembers As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSGender As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSMStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMStat As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSMNation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMNation As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSMinistry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMinistry As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSStatus As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSEdu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSEdu As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSBlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSBlood As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSProf As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSPosit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSPosit As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSDegree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSDegree As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSSkill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSSkill As Global.System.Web.UI.WebControls.SqlDataSource
End Class
