'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class References
    
    '''<summary>
    '''BtnNat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNat As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopNat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopNat As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVNation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVNation As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSNation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSNation As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnProf As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopProf As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVProf As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSProf As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnDegree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDegree As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopDegree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopDegree As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVNation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVNation1 As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSDegree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSDegree As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPos As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopPos As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPos As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSPos As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnMin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnMin As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVNation0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVNation0 As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSMinistry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMinistry As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRet As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopRet As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVRet As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSRet As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnSkill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSkill As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopSkill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopSkill As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVSkill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVSkill As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSSkill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSSkill As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDist As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopDist As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVDist As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSDist As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnEdu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEdu As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopEdu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEdu As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVEdu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVEdu As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSEdu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSEdu As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''BtnCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCity As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopCity0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopCity0 As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVCityD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVCityD As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSCityD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCityD As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''UPanParish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPanParish As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''BtnPar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPar As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopPar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopPar As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVPar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPar As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSPar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSPar As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSParCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSParCity As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSParDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSParDist As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnInt As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopInt As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVInterest As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSInterest As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnCrs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCrs As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopCrs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopCrs As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVCourse As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSCourse As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnAtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAtt As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopAtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopAtt As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVAtt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVAtt As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSAttend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSAttend As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BtnMis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnMis As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''PopMis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopMis As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''GVMis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVMis As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''DSMis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMis As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSMisCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMisCity As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DSMisDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSMisDist As Global.System.Web.UI.WebControls.SqlDataSource
End Class
